### ISSUE TITLE
Nested OU

### ISSUE THREAD

**Issue by emersonramos** [hashicorp/learn-terraform-aft-account-request#8]
Hi,

Please, I have any Nested OU on my AWS Org and I get error passing ManagedOrganizationalUnit value.

It's a limitation or It's possible to pass a Nested OU? I'm using the format: OU1/Nested_OU

Error:

InvalidParametersException  The parent organizational unit 'OU1/Nested_OU' is not enrolled in AWS Control Tower.

**Comment by ritsok** [comment]
Hi @emersonramos. 

Based on that error message, I wonder if you my need to enroll that organization in Control Tower. 

As for the specifics of what the module does or does not support, it would be best to post a question to the AWS team that maintains the module this tutorial uses: https://github.com/aws-ia/terraform-aws-control_tower_account_factory
